import { TYPES } from "../common/enums.js";

const TYPES_MAPPING = {
  'BUY - MARKET': TYPES.BUY,
  'SELL - MARKET': TYPES.SELL,
  'CUSTODY FEE': TYPES.CUSTODY_FEE,
  'DIVIDEND': TYPES.DIVIDEND,
  'CASH TOP-UP': TYPES.CASH_IN,
  'CASH WITHDRAWAL': TYPES.CASH_OUT,
  'STOCK SPLIT': TYPES.STOCK_SPLIT,
};

const DATE_FORMAT = 'YYYY-MM-DDTHH:mm:ss.SSSSSSZ';

const DIVIDEND_NET_RATE = 0.85;

export {
  TYPES_MAPPING,
  DATE_FORMAT,
  DIVIDEND_NET_RATE,
};